repos:
  - repo: local
    hooks:
      - id: pie-lint
        name: pie-lint
        entry: just lint
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]

      - id: pie-tests
        name: pie-tests (pre-push)
        entry: just test all
        language: system
        pass_filenames: false
        stages: [pre-push]
