[tooling]
node_min = "20.0.0"
npm_min = "10.0.0"
biome_min = "2.3.11"
typescript_min = "5.9.3"
vitest_min = "4.0.16"
eslint_min = "9.36.0"
prek_min = "0.3.0"
just_min = "1.38.0"
git_cliff_min = "2.10.0"
